---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  flake8
  ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community ANSIBLE_COLLECTIONS_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community-collections ansible-lint
platforms:
  - name: Fedora-Molecule-Directory
    box: fedora/34-cloud-base
    provider_options:
      cpus: 2
      memory: 2048
    provider_raw_config_args:
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}:../../../community
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
